# -*- coding: utf-8 -*-
"""task2_data_collection.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rdm6PB6i3Ose7Im98orM_wD-8-GLSF41
"""

# ============================================================
#   TASK 2: Data Cleaning & Preprocessing
#   Decodelabs Data Science Internship
#   Dataset: Titanic (via Seaborn)
# ============================================================

import pandas as pd
import seaborn as sns

# ── 1. LOAD DATASET ─────────────────────────────────────────
df = sns.load_dataset('titanic')
print("✅ Dataset loaded successfully!")
print(f"Original Shape: {df.shape}\n")

# ── 2. CHECK MISSING VALUES (BEFORE CLEANING) ────────────────
print("=" * 50)
print("❓ MISSING VALUES BEFORE CLEANING:")
print(df.isnull().sum())

# ── 3. HANDLE MISSING VALUES ─────────────────────────────────
print("\n" + "=" * 50)
print("🔧 HANDLING MISSING VALUES...")

# Fill missing 'age' with median (better than mean for skewed data)
df['age'] = df['age'].fillna(df['age'].median())
print(f"  ✔ 'age'      → filled with median: {df['age'].median()}")

# Fill missing 'embarked' with mode (most frequent value)
df['embarked'] = df['embarked'].fillna(df['embarked'].mode()[0])
print(f"  ✔ 'embarked' → filled with mode: '{df['embarked'].mode()[0]}'")

# Fill missing 'embark_town' with mode
df['embark_town'] = df['embark_town'].fillna(df['embark_town'].mode()[0])
print(f"  ✔ 'embark_town' → filled with mode")

# Drop 'deck' column — too many missing values (688 out of 891)
df.drop(columns=['deck'], inplace=True)
print(f"  ✔ 'deck'     → column dropped (too many missing values)")

# ── 4. REMOVE DUPLICATES ─────────────────────────────────────
print("\n" + "=" * 50)
print("🔍 CHECKING FOR DUPLICATES...")
duplicates = df.duplicated().sum()
print(f"  Duplicate rows found: {duplicates}")
df.drop_duplicates(inplace=True)
print(f"  ✔ Duplicates removed. New shape: {df.shape}")

# ── 5. FORMAT DATA CORRECTLY ─────────────────────────────────
print("\n" + "=" * 50)
print("🔄 FORMATTING DATA...")

# Encode 'sex' column: male=0, female=1
df['sex'] = df['sex'].map({'male': 0, 'female': 1})
print("  ✔ 'sex' encoded → male=0, female=1")

# Encode 'embarked' column: S=0, C=1, Q=2
df['embarked'] = df['embarked'].map({'S': 0, 'C': 1, 'Q': 2})
print("  ✔ 'embarked' encoded → S=0, C=1, Q=2")

# Convert 'pclass' to string category for clarity
df['pclass'] = df['pclass'].astype(str)
print("  ✔ 'pclass' converted to string type")

# ── 6. VERIFY CLEANING (AFTER) ───────────────────────────────
print("\n" + "=" * 50)
print("✅ MISSING VALUES AFTER CLEANING:")
print(df.isnull().sum())

print("\n📋 CLEANED DATASET SHAPE:", df.shape)
print("\n📋 CLEANED DATA TYPES:")
print(df.dtypes)

print("\n📋 FIRST 5 ROWS OF CLEANED DATA:")
print(df.head())

print("\n✅ Task 2 Complete! Dataset is clean and ready for analysis.")